on: [push]

jobs:
  hellow_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world actions step
      id: hello
      uses: ashthetis/my-javascript-action@v2
      with:
        who-to-great: 'ashthetis'
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time}}"
